# Generated by Django 5.0 on 2023-12-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('children', models.IntegerField()),
                ('charges', models.FloatField()),
                ('sex', models.IntegerField()),
                ('smoker', models.IntegerField()),
                ('region', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mammo_Mass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BI_RADS', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Shape', models.FloatField()),
                ('Margin', models.IntegerField()),
                ('Density', models.FloatField()),
                ('Severity', models.IntegerField()),
            ],
        ),
    ]
